
export enum RoleName {
  SUPER_ADMIN = 'SUPER_ADMIN',
  HR_ADMIN = 'HR_ADMIN',
  HR_EXECUTIVE = 'HR_EXECUTIVE',
  FINANCE = 'FINANCE',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  TEAM_LEADER = 'TEAM_LEADER',
  EMPLOYEE = 'EMPLOYEE'
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  INTERN = 'INTERN',
  CONTRACT = 'CONTRACT',
  CONSULTANT = 'CONSULTANT'
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  PROBATION = 'PROBATION',
  NOTICE_PERIOD = 'NOTICE_PERIOD',
  RESIGNED = 'RESIGNED',
  TERMINATED = 'TERMINATED',
  INACTIVE = 'INACTIVE'
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  HALF_DAY = 'HALF_DAY',
  LATE = 'LATE',
  LEAVE = 'LEAVE',
  WEEK_OFF = 'WEEK_OFF',
  HOLIDAY = 'HOLIDAY',
  WORK_FROM_HOME = 'WORK_FROM_HOME'
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}

export enum PayrollStatus {
  DRAFT = 'DRAFT',
  ATTENDANCE_CALCULATED = 'ATTENDANCE_CALCULATED',
  SALARY_CALCULATED = 'SALARY_CALCULATED',
  HR_REVIEWED = 'HR_REVIEWED',
  FINANCE_REVIEWED = 'FINANCE_REVIEWED',
  APPROVED = 'APPROVED',
  PROCESSED = 'PROCESSED'
}

export enum CandidateStatus {
  APPLIED = 'APPLIED',
  SCREENING = 'SCREENING',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEW = 'INTERVIEW',
  TECHNICAL_ROUND = 'TECHNICAL_ROUND',
  HR_ROUND = 'HR_ROUND',
  SELECTED = 'SELECTED',
  OFFERED = 'OFFERED',
  JOINED = 'JOINED',
  REJECTED = 'REJECTED'
}

export enum AssetStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  IN_USE = 'IN_USE',
  RETURNED = 'RETURNED',
  MAINTENANCE = 'MAINTENANCE',
  DISPOSED = 'DISPOSED'
}

export enum ExpenseStatus {
  PENDING = 'PENDING',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  FINANCE_APPROVED = 'FINANCE_APPROVED',
  REIMBURSED = 'REIMBURSED',
  REJECTED = 'REJECTED'
}

export enum ExitStatus {
  SUBMITTED = 'SUBMITTED',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  HR_APPROVED = 'HR_APPROVED',
  CLEARANCE_IN_PROGRESS = 'CLEARANCE_IN_PROGRESS',
  SETTLED = 'SETTLED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED'
}
