import { z } from 'zod';

export const createEmployeeSchema = z.object({
  email: z.string().email(),
  password: z.string().optional(),
  firstName: z.string().min(1).optional(),
  lastName: z.string().optional(),
  fullName: z.string().optional(),
  employeeCode: z.string().optional(),
  role: z.string().optional(),
  departmentId: z.string().uuid().optional(),
  designationId: z.string().uuid().optional(),
  department: z.string().optional(),
  designation: z.string().optional(),
  specialization: z.string().optional(),
  teamId: z.string().optional(),
  employmentType: z.string().optional(),
  joiningDate: z.string().optional(),
  mobileNumber: z.string().optional(),
  mobile: z.string().optional(),
  ctc: z.number().optional(),
  baseSalary: z.number().optional(),
  bankAccountNo: z.string().optional(),
  accountNumber: z.string().optional(),
  ifscCode: z.string().optional(),
  ifsc: z.string().optional(),
  bankName: z.string().optional(),
  pan: z.string().optional(),
  uan: z.string().optional(),
  dateOfBirth: z.string().optional(),
  gender: z.string().optional(),
  emergencyContact: z.string().optional(),
  emergencyPhone: z.string().optional(),
  address: z.string().optional(),
  notes: z.string().optional(),
});

export const updateEmployeeSchema = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  gender: z.string().optional(),
  dateOfBirth: z.string().optional(),
  mobileNumber: z.string().optional(),
  personalEmail: z.string().email().optional(),
  address: z.string().optional(),
  departmentId: z.string().uuid().nullable().optional(),
  teamId: z.string().uuid().nullable().optional(),
  designationId: z.string().uuid().nullable().optional(),
  reportingManagerId: z.string().uuid().nullable().optional(),
  employmentType: z.string().optional(),
  workLocation: z.string().optional(),
  workMode: z.string().optional(),
  status: z.string().optional(),
  bankAccountNo: z.string().optional(),
  ifscCode: z.string().optional(),
  bankName: z.string().optional(),
  accountHolder: z.string().optional(),
  emergencyContactName: z.string().optional(),
  emergencyRelation: z.string().optional(),
  emergencyPhone: z.string().optional(),
  profilePhoto: z.string().optional(),
});

export type CreateEmployeeDto = z.infer<typeof createEmployeeSchema>;
export type UpdateEmployeeDto = z.infer<typeof updateEmployeeSchema>;
